### ISSUE TITLE
Sample-apk under releases for easy try

### ISSUE THREAD

**Issue by Rainer-Lang** [blipinsk/RxAnimationBinding#1]

**Comment by blipinsk** [comment]
Hi, thanks for your request.
I don't see `sample` changing much from release to release... Therefore including the same apk or almost the same apk in releases seems pointless to me. More so, let's be honest, the most important part of the `sample` is not the interface so is not the thing you will see when you install an apk. The most important part is the code. So trying out an apk won't give anybody much.

**Comment by Rainer-Lang** [comment]
@blipinsk You're right. In your lib the code is really more interesting instead of a sample interface. Interesting lib btw. :)

**Comment by blipinsk** [comment]
Thanks for an interesting idea anyways! :+1:
